/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESTests */

#ifndef _Included_AESTests
#define _Included_AESTests
#ifdef __cplusplus
extern "C" {
#endif
#undef AESTests_BLKLEN
#define AESTests_BLKLEN 16L
/*
 * Class:     AESTests
 * Method:    OPENSSL_CTR_CTX_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_AESTests_OPENSSL_1CTR_1CTX_1create
  (JNIEnv *, jclass);

/*
 * Class:     AESTests
 * Method:    OPENSSL_CTR_CTX_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_AESTests_OPENSSL_1CTR_1CTX_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     AESTests
 * Method:    OPENSSL_CTR_CTX_compute
 * Signature: (J[B[B[BII)Z
 */
JNIEXPORT jboolean JNICALL Java_AESTests_OPENSSL_1CTR_1CTX_1compute
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
