/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HMACSHA1Tests */

#ifndef _Included_HMACSHA1Tests
#define _Included_HMACSHA1Tests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HMACSHA1Tests
 * Method:    OPENSSL_HMACSHA1_CTX_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HMACSHA1Tests_OPENSSL_1HMACSHA1_1CTX_1create
  (JNIEnv *, jclass);

/*
 * Class:     HMACSHA1Tests
 * Method:    OPENSSL_HMACSHA1_CTX_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HMACSHA1Tests_OPENSSL_1HMACSHA1_1CTX_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HMACSHA1Tests
 * Method:    OPENSSL_HMACSHA1_CTX_init
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_HMACSHA1Tests_OPENSSL_1HMACSHA1_1CTX_1init
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     HMACSHA1Tests
 * Method:    OPENSSL_HMACSHA1_CTX_process
 * Signature: (J[BIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_HMACSHA1Tests_OPENSSL_1HMACSHA1_1CTX_1process
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     HMACSHA1Tests
 * Method:    OPENSSL_HMACSHA1_process
 * Signature: ([B[BIII)Z
 */
JNIEXPORT jboolean JNICALL Java_HMACSHA1Tests_OPENSSL_1HMACSHA1_1process
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
